// <auto-generated />
using System;
using BarberSalon.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarberSalon.Migrations
{
    [DbContext(typeof(BarberSalonContext))]
    [Migration("20260419193724_ReviewTableEdit")]
    partial class ReviewTableEdit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BarberSalon.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("AppointmentTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("BarberSalon.Models.PortofolioItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("WorkerId");

                    b.ToTable("PortofolioItem");
                });

            modelBuilder.Entity("BarberSalon.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Review");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Ion Popescu",
                            Comment = "Cel mai bun frizer din oraș! Întotdeauna lasă cu un zâmbet și serviciul este impecabil. Recomand cu tărie!",
                            Rating = 5,
                            ServiceId = 1,
                            UserId = 1,
                            WorkerId = 1
                        },
                        new
                        {
                            Id = 2,
                            Author = "Maria Ionescu",
                            Comment = "Servicii de top și atmosferă prietenoasă. Mă simt relaxată și bine tratată de fiecare dată. Recomand cu căldură!",
                            Rating = 5,
                            ServiceId = 2,
                            UserId = 1,
                            WorkerId = 1
                        },
                        new
                        {
                            Id = 3,
                            Author = "Vasile Georgescu",
                            Comment = "Întotdeauna mă simt proaspăt și încrezător după o vizită. Profesioniștii sunt atenți la detalii și foarte courtezi.",
                            Rating = 5,
                            ServiceId = 1,
                            UserId = 1,
                            WorkerId = 2
                        },
                        new
                        {
                            Id = 4,
                            Author = "Alexandru Mihai",
                            Comment = "Calitate impecabilă! Am găsit în sfârșit un salon unde mă simt acasă. Echipa este foarte profesionistă și amabilă.",
                            Rating = 5,
                            ServiceId = 5,
                            UserId = 1,
                            WorkerId = 1
                        },
                        new
                        {
                            Id = 5,
                            Author = "Cristina Popescu",
                            Comment = "Sunt client fidel de mai bine de un an. Mereu mă surprinde cu atenția la detalii și creativitate. Superb!",
                            Rating = 5,
                            ServiceId = 1,
                            UserId = 1,
                            WorkerId = 2
                        },
                        new
                        {
                            Id = 6,
                            Author = "Daniel Stancu",
                            Comment = "Cel mai profesionist salon din Craiova! Recomand cu încredere oricui caută un serviciu de calitate.",
                            Rating = 5,
                            ServiceId = 2,
                            UserId = 1,
                            WorkerId = 3
                        },
                        new
                        {
                            Id = 7,
                            Author = "Andrei Popescu",
                            Comment = "Masajul scalp este absolut relaxant. Echipa este super profesionistă și amabilă. Voi reveni cu siguranță!",
                            Rating = 5,
                            ServiceId = 3,
                            UserId = 1,
                            WorkerId = 1
                        },
                        new
                        {
                            Id = 8,
                            Author = "Elena Vlăduț",
                            Comment = "Tratamentul păr este foarte eficient. Părul meu se simte mult mai moale și ușor de coafat după tratament.",
                            Rating = 4,
                            ServiceId = 6,
                            UserId = 1,
                            WorkerId = 2
                        });
                });

            modelBuilder.Entity("BarberSalon.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Service");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Tuns modern, adaptat preferințelor tale",
                            Name = "Tuns Barbat",
                            Price = 50
                        },
                        new
                        {
                            Id = 2,
                            Description = "Tuns complet cu ras și îngrijire a bărbii",
                            Name = "Tuns Barbat + Barba",
                            Price = 70
                        },
                        new
                        {
                            Id = 3,
                            Description = "Spălare și massage pentru relaxare",
                            Name = "Spalat",
                            Price = 30
                        },
                        new
                        {
                            Id = 4,
                            Description = "Vopsire păr cu produse profesionale",
                            Name = "Vopsit",
                            Price = 60
                        },
                        new
                        {
                            Id = 5,
                            Description = "Ras și îngrijire profesională a bărbii",
                            Name = "Barba",
                            Price = 40
                        },
                        new
                        {
                            Id = 6,
                            Description = "Tratament hidratant și nutritiv pentru păr",
                            Name = "Tratament Păr",
                            Price = 45
                        },
                        new
                        {
                            Id = 7,
                            Description = "Aplicare produse de finisare și styling",
                            Name = "Pomadă",
                            Price = 15
                        },
                        new
                        {
                            Id = 8,
                            Description = "Tunsoare specială pentru copii cu îngrijire",
                            Name = "Tuns Copil",
                            Price = 35
                        },
                        new
                        {
                            Id = 9,
                            Description = "Masaj relaxant cu produse profesionale",
                            Name = "Masaj Scalp",
                            Price = 50
                        });
                });

            modelBuilder.Entity("BarberSalon.Models.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Worker");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Strada Primaverii, Craiova",
                            HireDate = new DateTime(2014, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Andrei Popescu",
                            PhoneNumber = 740123456,
                            Position = "Frizer Senior"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Strada Primaverii, Craiova",
                            HireDate = new DateTime(2016, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mihai Ionescu",
                            PhoneNumber = 740123457,
                            Position = "Frizer Specialist"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Strada Primaverii, Craiova",
                            HireDate = new DateTime(2018, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cristian Georgescu",
                            PhoneNumber = 740123458,
                            Position = "Frizer"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Strada Primaverii, Craiova",
                            HireDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Daniel Vasilescu",
                            PhoneNumber = 740123459,
                            Position = "Frizer Apprentice"
                        });
                });

            modelBuilder.Entity("BarberSalon.Models.Appointment", b =>
                {
                    b.HasOne("BarberSalon.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberSalon.Models.Worker", "Worker")
                        .WithMany("Appointments")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("BarberSalon.Models.PortofolioItem", b =>
                {
                    b.HasOne("BarberSalon.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberSalon.Models.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("BarberSalon.Models.Review", b =>
                {
                    b.HasOne("BarberSalon.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberSalon.Models.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("BarberSalon.Models.Worker", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
